name: Pull request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node_modules
        run: if [ ! -d ./node_modules ]; then npm ci; fi
      - name: Test
        run: cat ./.github/workflows/tests.yml
      - uses: ./.github/workflows/tests
