name: Pull request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          fetch-depth: 0
      - uses: ./.github/workflows/tests.yml
