name: Release

concurrency:
  group: release
  cancel-in-progress: false

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    uses: ./.github/workflows/build-tests.yml

  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Load build output
        uses: actions/cache@v2
        env:
          cache-name: cache-dist
        with:
          path: ./dist
          key: lib-${{ hashFiles('./lib/**') }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Publish the package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
    needs:
      - tests
